server:
  port: 8082
spring:
  rabbitmq:
    addresses: 139.196.202.130
    username: admin
    password: admin
    virtual-host: /test
  application:
    name: dp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.202.130:5306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: g123456
  redis:
    host: 139.196.202.130
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis-plus:
  type-aliases-package: con.dp.entity # 别名扫描包
logging:
  level:
    com.dp: debug

