server:
  port: 8081
spring:
  rabbitmq:
    addresses: 192.168.85.129
    username: admin
    password: admin
    virtual-host: /test
  application:
    name: dp-profile
    config:
      use-legacy-processing: true
    profiles:
      active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: g123456
  redis:
    host: 192.168.85.131
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis-plus:
  type-aliases-package: con.dp.entity # 别名扫描包
logging:
  level:
    com.dp: debug

